"""
Bindings PyBind11 per il simulatore x86-64
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['ALU', 'Bus', 'CPU', 'CacheManager', 'Clock', 'Memory', 'Pipeline', 'RegisterFile']
class ALU:
    pass
class Bus:
    def __init__(self) -> None:
        ...
    def getCPU(self) -> CPU:
        ...
    def getClock(self) -> Clock:
        ...
    def getMemory(self) -> Memory:
        ...
    def memoryReset(self) -> None:
        ...
    def resetClock(self) -> None:
        ...
    def tick(self) -> None:
        ...
class CPU:
    def cpuReset(self) -> None:
        ...
    def cpuStart(self) -> None:
        ...
    def cpuStep(self) -> None:
        ...
    def getALU(self) -> ALU:
        ...
    def getCacheManager(self) -> CacheManager:
        ...
    def getControlUnit(self) -> CU:
        ...
    def getInstructionIdCounter(self) -> int:
        ...
    def getPipeline(self) -> Pipeline:
        ...
    def getRegisters(self) -> RegisterFile:
        ...
    def incrementInstructionIdCounter(self) -> None:
        ...
class CacheManager:
    pass
class Clock:
    def __init__(self) -> None:
        ...
    def getCycles(self) -> int:
        ...
    def reset(self) -> None:
        ...
    def tick(self) -> None:
        ...
class Memory:
    def clear(self) -> None:
        ...
    def getBasePointer(self) -> int:
        ...
    def getData(self) -> list[int]:
        ...
    def getSize(self) -> int:
        ...
    def getStackPointer(self) -> int:
        ...
    def pop(self) -> ...:
        ...
    def push(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> ...:
        ...
    def setBasePointer(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def setData(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def setStackPointer(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class Pipeline:
    pass
class RegisterFile:
    pass
